---
/**:
  ros__parameters:
    port: "$(var laser_uri)"
    frame_id: "$(var laser_id)_link"
    ignore_array: ""
    baudrate: 115200
    lidar_type: 1
    device_type: 0
    sample_rate: 3
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: false
    inverted: false
    auto_reconnect: true
    isSingleChannel: true
    intensity_bit: 0
    intensity: false
    support_motor_dtr: true
    angle_max: $(var laser_max_angle_deg)
    angle_min: $(var laser_min_angle_deg)
    range_max: 12.0
    range_min: 0.1
    frequency: 10.0
    invalid_range_is_inf: false
    debug: false
