left_wheel_joint: left_wheel_joint
right_wheel_joint: right_wheel_joint
# Note: serial_port is provided at launch time through driver_uri/ROBOT_BASE_DRIVER_URI
serial_baudrate: "115200"
serial_timeout: "1000"
resolution: "585"