robot_radius: 0.06
#footprint: [[-0.1, -0.125], [-0.1, 0.125], [0.1, 0.125], [0.1, -0.125]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.15

obstacle_layer:
  obstacle_range: 0.5
  raytrace_range: 1.5
  observation_sources: front_laser 
  front_laser: 
    sensor_frame: $(arg prefix)front_laser_link  
    data_type: LaserScan
    topic: $(arg scan_topic)        
    marking: true
    clearing: true

