robot_radius: 0.06
#footprint: [[-0.1, -0.125], [-0.1, 0.125], [0.1, 0.125], [0.1, -0.125]]

publish_frequency: 1.0

obstacle_layer:
  obstacle_range: 5.0
  raytrace_range: 5.0
  observation_sources: front_laser 
  front_laser: 
    sensor_frame: $(arg prefix)front_laser_link  
    data_type: LaserScan
    topic: $(arg scan_topic)        
    marking: true
    clearing: true

