global_costmap:
  global_frame: $(arg prefix)map                
  robot_base_frame: $(arg footprint_frame)  
  update_frequency: 2.0
  static_map: true
  width: 4.0      # Local costmap size 
  height: 4.0     # Local costmap size
  resolution: 0.05 

  plugins:
    - 
      name: static_map
      type: "costmap_2d::StaticLayer"
    -
      name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - 
      name: inflation_layer
      type: "costmap_2d::InflationLayer"
  
  static_map:
      lethal_cost_threshold: 94
      static_map: true
      track_unknown_space: false
      unknown_cost_value: 1
      trinary_costmap: false
      use_maximum: false
      map_topic: map                 

  inflation_layer:
      cost_scaling_factor: 20.0
      inflation_radius: 0.15
    
