global_costmap:
  global_frame: $(arg prefix)map                
  robot_base_frame: $(arg footprint_frame)  
  update_frequency: 2.0
  width: 7.0      # Local costmap size 
  height: 7.0     # Local costmap size
  resolution: 0.01 

  plugins:
    - 
      name: static_map
      type: "costmap_2d::StaticLayer"
    - 
      name: inflation_layer
      type: "costmap_2d::InflationLayer"
  
  inflation_layer:
      cost_scaling_factor: 0.0
      inflation_radius: 0.1
    
