local_costmap:
  global_frame: $(arg odom_frame)              
  robot_base_frame: $(arg footprint_frame) 
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 4.0      # Local costmap size 
  height: 4.0     # Local costmap size
  resolution: 0.05 
  
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    -
      name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - 
      name: inflation_layer
      type: "costmap_2d::InflationLayer"

  inflation_layer:
      cost_scaling_factor: 20.0
      inflation_radius: 0.05
    
